### ISSUE TITLE
Análisis: Posibles soluciones para landing page.

### ISSUE THREAD

**Issue by RileyBlue** [ReactiveTech/reactive-landing#1]
- Analizar si se llevarán a cabo mockups o se utilizará Startup Framework para desarrollo de la landing de ReactiveTech y de LookUp.

**Comment by RileyBlue** [comment]
¿Qué opinas @UchihaCFC, tenemos las opciones de desarrollar la landing desde cero y la otra es utilizar la herramienta de Startup Framework para crear una landing momentánea?

**Comment by UchihaCFC** [comment]
@OmarSainz si queremos ir rápido optaría por la Startup Framework y asi la aprovechamos, cuando tengamos algo más de tiempo podemos hacerla con materialize, aunque si sacas algo de tiempo esta semana y pudieramos definir el diseño de la land, me comprometo a maquetarla. Yo es que el diseño me demoraría muchísimo

**Comment by RileyBlue** [comment]
@UchihaCFC sí, es que el Diseño es más tardado. Chequemos si alguna de las opciones de la Startup Framework nos convence y vamos por ello, si no... Yo hago el diseño, pero lo que más me interesa es que no nos detengamos mucho ahorita a meterle mucho detalle a la landing o cualquier cosa que hagamos, sino que hagamos cosas rápidas, sencillas y que podamos mostrar algo a la gente.

**Comment by UchihaCFC** [comment]
@OmarSainz cuando quieras quedamos y miramos ;)
